import 'package:gym/widgets/app_bar/custom_app_bar.dart';import 'package:gym/widgets/app_bar/appbar_subtitle.dart';import 'package:gym/widgets/custom_text_form_field.dart';import 'package:gym/core/utils/validation_functions.dart';import 'package:gym/widgets/custom_elevated_button.dart';import 'models/create_profile_confirm_model.dart';import 'package:flutter/material.dart';import 'package:gym/core/app_export.dart';import 'bloc/create_profile_confirm_bloc.dart';import 'package:gym/presentation/congratulation_dialog/congratulation_dialog.dart';
// ignore_for_file: must_be_immutable
class CreateProfileConfirmScreen extends StatelessWidget {CreateProfileConfirmScreen({Key? key}) : super(key: key, );

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<CreateProfileConfirmBloc>(create: (context) => CreateProfileConfirmBloc(CreateProfileConfirmState(createProfileConfirmModelObj: CreateProfileConfirmModel(), ))..add(CreateProfileConfirmInitialEvent()), child: CreateProfileConfirmScreen(), ); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: SizeUtils.width, child: SingleChildScrollView(padding: EdgeInsets.only(bottom: MediaQuery.of(context).viewInsets.bottom, ), child: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 6.v, ), child: Column(children: [Container(width: 329.h, margin: EdgeInsets.symmetric(horizontal: 12.h), child: Text("msg_please_enter_your3".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyLarge, ), ), SizedBox(height: 20.v), CustomImageView(imagePath: ImageConstant.imgIconContainer, height: 80.adaptSize, width: 80.adaptSize, radius: BorderRadius.circular(40.h, ), ), SizedBox(height: 11.v), Text("lbl_add_photo".tr, style: CustomTextStyles.titleMedium18, ), SizedBox(height: 5.v), Text("msg_this_will_be_your".tr, style: theme.textTheme.titleSmall, ), SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_name".tr, style: theme.textTheme.titleMedium, ), ), SizedBox(height: 7.v), _buildName(context), SizedBox(height: 14.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_phone_number".tr, style: theme.textTheme.titleMedium, ), ), SizedBox(height: 5.v), _buildPhoneNumber(context), SizedBox(height: 11.v), Align(alignment: Alignment.centerLeft, child: Text("lbl_email".tr, style: theme.textTheme.titleMedium, ), ), SizedBox(height: 8.v), _buildEmail(context), SizedBox(height: 5.v)], ), ), ), ), ), bottomNavigationBar: _buildGetStared(context), ), ); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(centerTitle: true, title: AppbarSubtitle(text: "lbl_create_profile".tr, ), ); } 
/// Section Widget
Widget _buildName(BuildContext context) { return BlocSelector<CreateProfileConfirmBloc, CreateProfileConfirmState, TextEditingController?>(selector: (state) => state.nameController, builder: (context, nameController) {return CustomTextFormField(controller: nameController, hintText: "lbl_hager".tr, );}, ); } 
/// Section Widget
Widget _buildPhoneNumber(BuildContext context) { return BlocSelector<CreateProfileConfirmBloc, CreateProfileConfirmState, TextEditingController?>(selector: (state) => state.phoneNumberController, builder: (context, phoneNumberController) {return CustomTextFormField(controller: phoneNumberController, hintText: "msg_20_112_428_7083".tr, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 12.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgIconOnprimarycontainer, height: 20.adaptSize, width: 20.adaptSize, ), ), suffixConstraints: BoxConstraints(maxHeight: 45.v, ), contentPadding: EdgeInsets.only(left: 12.h, top: 12.v, bottom: 12.v, ), );}, ); } 
/// Section Widget
Widget _buildEmail(BuildContext context) { return BlocSelector<CreateProfileConfirmBloc, CreateProfileConfirmState, TextEditingController?>(selector: (state) => state.emailController, builder: (context, emailController) {return CustomTextFormField(controller: emailController, hintText: "lbl_ahmed_gamil_com".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.emailAddress, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 12.v, 12.h, 12.v), child: CustomImageView(imagePath: ImageConstant.imgIconOnprimarycontainer, height: 20.adaptSize, width: 20.adaptSize, ), ), suffixConstraints: BoxConstraints(maxHeight: 45.v, ), validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;}, contentPadding: EdgeInsets.only(left: 12.h, top: 12.v, bottom: 12.v, ), );}, ); } 
/// Section Widget
Widget _buildGetStared(BuildContext context) { return CustomElevatedButton(text: "lbl_get_stared".tr, margin: EdgeInsets.only(left: 18.h, right: 18.h, bottom: 58.v, ), onPressed: () {onTapGetStared(context);}, ); } 

/// Displays a dialog with the [CongratulationDialog] content.
onTapGetStared(BuildContext context) { showDialog(context: NavigatorService.navigatorKey.currentContext!, builder: (_) => AlertDialog(content: CongratulationDialog.builder(NavigatorService.navigatorKey.currentContext!),backgroundColor: Colors.transparent, contentPadding: EdgeInsets.zero, insetPadding: const EdgeInsets.only(left: 0),)); } 
 }
