import 'package:gym/widgets/app_bar/custom_app_bar.dart';import 'package:gym/widgets/app_bar/appbar_leading_image.dart';import 'package:gym/widgets/custom_pin_code_text_field.dart';import 'package:gym/widgets/custom_elevated_button.dart';import 'models/verification_code_enter_model.dart';import 'package:flutter/material.dart';import 'package:gym/core/app_export.dart';import 'bloc/verification_code_enter_bloc.dart';class VerificationCodeEnterScreen extends StatelessWidget {const VerificationCodeEnterScreen({Key? key}) : super(key: key, );

static Widget builder(BuildContext context) { return BlocProvider<VerificationCodeEnterBloc>(create: (context) => VerificationCodeEnterBloc(VerificationCodeEnterState(verificationCodeEnterModelObj: VerificationCodeEnterModel(), ))..add(VerificationCodeEnterInitialEvent()), child: VerificationCodeEnterScreen(), ); } 
@override Widget build(BuildContext context) { return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 18.h, vertical: 46.v, ), child: Column(children: [Text("msg_enter_verification".tr, style: theme.textTheme.headlineSmall, ), SizedBox(height: 10.v), SizedBox(height: 49.v, width: 299.h, child: Stack(alignment: Alignment.bottomRight, children: [Align(alignment: Alignment.center, child: SizedBox(width: 299.h, child: Text("msg_we_ve_sent_an_otp".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyLarge, ), ), ), CustomImageView(imagePath: ImageConstant.imgSolarPen2Outline, height: 16.adaptSize, width: 16.adaptSize, alignment: Alignment.bottomRight, margin: EdgeInsets.only(right: 48.h, bottom: 4.v, ), onTap: () {onTapImgSolarPenOutline(context);}, )], ), ), SizedBox(height: 29.v), Padding(padding: EdgeInsets.symmetric(horizontal: 43.h), child: BlocSelector<VerificationCodeEnterBloc, VerificationCodeEnterState, TextEditingController?>(selector: (state) => state.otpController, builder: (context, otpController) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;}, );}, ), ), SizedBox(height: 17.v), RichText(text: TextSpan(children: [TextSpan(text: "msg_the_remaining_time2".tr, style: CustomTextStyles.bodyMediumff030303, ), TextSpan(text: "lbl_00m_00s".tr, style: CustomTextStyles.bodyMediumff056aff, )], ), textAlign: TextAlign.left, ), SizedBox(height: 88.v), RichText(text: TextSpan(children: [TextSpan(text: "lbl_don_t_get_code".tr, style: CustomTextStyles.bodyMediumff92929d, ), TextSpan(text: "lbl_resend".tr, style: CustomTextStyles.titleSmallff056aff, )], ), textAlign: TextAlign.left, ), SizedBox(height: 10.v), CustomElevatedButton(text: "lbl_verify".tr, buttonTextStyle: CustomTextStyles.titleMediumGray5001Bold, onPressed: () {onTapVerify(context);}, ), SizedBox(height: 5.v)], ), ), ), ); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 44.v, leadingWidth: 389.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgVectorOnerrorcontainer20x9, margin: EdgeInsets.fromLTRB(23.h, 12.v, 357.h, 12.v), ), ); } 
/// Navigates to the signUpScreen when the action is triggered.
onTapImgSolarPenOutline(BuildContext context) { NavigatorService.pushNamed(AppRoutes.signUpScreen, ); } 
/// Navigates to the createAPasswordScreen when the action is triggered.
onTapVerify(BuildContext context) { NavigatorService.pushNamed(AppRoutes.createAPasswordScreen, ); } 
 }
